CREATE TABLE event_waiting_room_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events (id),
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    batch_size INTEGER NOT NULL,
    active_capacity INTEGER NOT NULL,
    admission_ttl_seconds BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_waiting_room_policy_event UNIQUE (event_id),
    CONSTRAINT ck_waiting_room_policy_batch CHECK (batch_size BETWEEN 1 AND 10000),
    CONSTRAINT ck_waiting_room_policy_capacity CHECK (active_capacity BETWEEN 1 AND 100000),
    CONSTRAINT ck_waiting_room_policy_batch_capacity CHECK (batch_size <= active_capacity),
    CONSTRAINT ck_waiting_room_policy_ttl CHECK (admission_ttl_seconds BETWEEN 10 AND 3600)
);

CREATE INDEX idx_waiting_room_policy_enabled
    ON event_waiting_room_policies (event_id)
    WHERE enabled = TRUE;
