CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_members_email UNIQUE (email),
    CONSTRAINT ck_members_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE artists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_artists_name UNIQUE (name)
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_id BIGINT NOT NULL REFERENCES artists (id),
    title VARCHAR(200) NOT NULL,
    description TEXT,
    event_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    sales_start_at TIMESTAMPTZ NOT NULL,
    sales_end_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_events_type CHECK (event_type IN ('CONCERT', 'FAN_MEETING', 'PUBLIC_BROADCAST', 'MERCHANDISE')),
    CONSTRAINT ck_events_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ON_SALE', 'CLOSED', 'CANCELLED')),
    CONSTRAINT ck_events_sales_period CHECK (sales_start_at < sales_end_at)
);

CREATE INDEX idx_events_public_list
    ON events (status, sales_start_at DESC, id DESC);

CREATE INDEX idx_events_artist
    ON events (artist_id, id DESC);

CREATE TABLE event_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events (id),
    name VARCHAR(120) NOT NULL,
    venue VARCHAR(200),
    starts_at TIMESTAMPTZ NOT NULL,
    sales_start_at TIMESTAMPTZ NOT NULL,
    sales_end_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_event_sessions_event_name UNIQUE (event_id, name),
    CONSTRAINT ck_event_sessions_sales_period CHECK (sales_start_at < sales_end_at)
);

CREATE INDEX idx_event_sessions_event_starts_at
    ON event_sessions (event_id, starts_at, id);

CREATE TABLE sellable_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_session_id BIGINT NOT NULL REFERENCES event_sessions (id),
    inventory_type VARCHAR(30) NOT NULL,
    name VARCHAR(150) NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    total_quantity INTEGER NOT NULL,
    available_quantity INTEGER NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_inventory_session_name UNIQUE (event_session_id, name),
    CONSTRAINT ck_inventory_type CHECK (inventory_type IN ('GENERAL_ADMISSION', 'MERCHANDISE')),
    CONSTRAINT ck_inventory_price CHECK (price >= 0),
    CONSTRAINT ck_inventory_total_quantity CHECK (total_quantity >= 0),
    CONSTRAINT ck_inventory_available_quantity CHECK (
        available_quantity >= 0 AND available_quantity <= total_quantity
    )
);

CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members (id),
    status VARCHAR(20) NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    confirmed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    expired_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_reservations_status CHECK (status IN ('PENDING', 'CONFIRMED', 'EXPIRED', 'CANCELLED', 'FAILED')),
    CONSTRAINT ck_reservations_total_amount CHECK (total_amount >= 0)
);

CREATE INDEX idx_reservations_member_created
    ON reservations (member_id, created_at DESC, id DESC);

CREATE INDEX idx_reservations_expiration
    ON reservations (expires_at, id)
    WHERE status = 'PENDING';

CREATE TABLE reservation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL REFERENCES reservations (id),
    inventory_id BIGINT NOT NULL REFERENCES sellable_inventory (id),
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_reservation_items_inventory UNIQUE (reservation_id, inventory_id),
    CONSTRAINT ck_reservation_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_reservation_items_unit_price CHECK (unit_price >= 0)
);

CREATE TABLE idempotency_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members (id),
    request_scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    response_status INTEGER,
    response_body JSONB,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_idempotency_member_scope_key UNIQUE (member_id, request_scope, idempotency_key)
);

CREATE INDEX idx_idempotency_expiration
    ON idempotency_requests (expires_at, id);

CREATE TABLE outbox_events (
    id UUID PRIMARY KEY,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id VARCHAR(80) NOT NULL,
    event_type VARCHAR(120) NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_outbox_status CHECK (status IN ('PENDING', 'PROCESSING', 'PUBLISHED', 'FAILED')),
    CONSTRAINT ck_outbox_attempts CHECK (attempts >= 0)
);

CREATE INDEX idx_outbox_polling
    ON outbox_events (available_at, created_at)
    WHERE status IN ('PENDING', 'FAILED');

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_member_id BIGINT REFERENCES members (id),
    action VARCHAR(100) NOT NULL,
    target_type VARCHAR(80) NOT NULL,
    target_id VARCHAR(80) NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_logs_target
    ON audit_logs (target_type, target_id, created_at DESC);
